# fly.toml app configuration file generated for pochamatch-backend
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'pochamatch-backend'
primary_region = 'sjc'

[build]

[deploy]
  release_command = 'echo "No release command needed"'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
